server.port=9004

#MySql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://restcuenta6-luis-990a.a.aivencloud.com:26490/tallermoto_db?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ew48yHlQyeNwveXDqRO

#Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
